// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import db "github.com/codystringham/mockingjay/db"
import mock "github.com/stretchr/testify/mock"

// UseCaseRepo is an autogenerated mock type for the UseCaseRepo type
type UseCaseRepo struct {
	mock.Mock
}

// GetTodo provides a mock function with given fields: _a0
func (_m *UseCaseRepo) GetTodo(_a0 int) (db.Todo, error) {
	ret := _m.Called(_a0)

	var r0 db.Todo
	if rf, ok := ret.Get(0).(func(int) db.Todo); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(db.Todo)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
